project_id = "aedpckxjyyklqwrzrnmg"

[functions.parent-chat]
verify_jwt = false

[functions.send-booking-notification]
verify_jwt = false

[functions.submit-booking]
verify_jwt = false

[functions.send-welcome-email]
verify_jwt = false

[functions.send-password-reset-email]
verify_jwt = false

[functions.send-contact-email]
verify_jwt = false

[functions.validate-file-upload]
verify_jwt = true

[functions.newsletter-subscribe]
verify_jwt = false

[functions.newsletter-confirm]
verify_jwt = false

[functions.newsletter-unsubscribe]
verify_jwt = false

[functions.newsletter-send]
verify_jwt = true

[functions.stripe-get-products]
verify_jwt = false

[functions.stripe-create-checkout]
verify_jwt = false

[functions.create-jira-ticket]
verify_jwt = false

[functions.generate-sitemap]
verify_jwt = false

[functions.check-login-attempts]
verify_jwt = false
